# Generated by Django 2.1.7 on 2019-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
